from __future__ import annotations

FORBIDDEN_PATTERNS = [
    "http://",
    "https://",
    "wikipedia",
    "youtube",
    "doi.org",
    "references",
    "bibliography",
    "further reading",
]

GENERIC_SECTION_TITLES = {
    "introduction",
    "overview",
    "conclusion",
    "summary",
    "references",
    "bibliography",
    "further reading",
}

ACTION_VERBS = {
    "use",
    "reduce",
    "increase",
    "insert",
    "introduce",
    "build",
    "schedule",
    "design",
    "align",
    "avoid",
    "simplify",
    "rotate",
    "time",
    "pair",
    "deploy",
    "adjust",
    "trigger",
    "reinforce",
    "install",
    "implement",
    "train",
    "establish",
    "compare",
    "measure",
    "identify",
    "scale",
    "guide",
    "provide",
    "communicate",
    "integrate",
    "position",
    "activate",
    "maintain",
    "monitor",
}

MEASURABLE_TERMS = {
    "rate",
    "score",
    "count",
    "level",
    "velocity",
    "density",
    "duration",
    "time",
    "frequency",
    "occupancy",
    "spend",
    "revenue",
    "sales",
    "intent",
    "temperature",
    "volume",
    "noise",
    "engagement",
    "fatigue",
}

TEMPORAL_TERMS = {
    "transition",
    "duration",
    "sequence",
    "phase",
    "state",
    "recovery",
    "lag",
    "minutes",
    "hours",
    "before",
    "after",
    "progression",
}

RELATIONSHIP_VOCAB = {
    "increases",
    "decreases",
    "leads_to",
    "amplifies",
    "suppresses",
    "accelerates",
    "delays",
    "destabilizes",
    "stabilizes",
    "buffers",
    "primes",
    "fatigues",
    "restores",
    "reinforces",
    "disrupts",
    "drives",
    "correlates_with",
    "predicts",
    "reduces",
    "decision_rule",
}

EVIDENCE_SOURCE_TYPES = {
    "peer_reviewed_experimental",
    "peer_reviewed_observational",
    "neuroscience",
    "hospitality_operational",
    "anecdotal_operator",
    "online_behavioral",
    "social_proof",
    "speculative",
}
